<template>
    <header>
        <h1>ALGORAND WALLET</h1>
        <h3>STEP 3 of 10</h3>
    </header>
    <p>
        <strong>As the first action, you need to download and install the app <a href="https://perawallet.app/" target="_blank">Pera Algo Wallet</a> on your phone.</strong>
        <br><br>
        Here is an article on how to set up your Pera Algo Wallet:
        <br><br>
        <a href="https://support.perawallet.app/en/article/create-a-new-algorand-account-on-pera-wallet-1ehbj11/" target="_blank">https://support.perawallet.app/en/article/create-a-new-algorand-account-on-pera-wallet-1ehbj11/</a>
        <br><br>
        IMPORTANT NOTE: Ensure to save your seed phrase (a series of words generated by your cryptocurrency wallet that give you
        access to the crypto associated with that wallet) in a secure location because you will need access to this in the
        future.
        <br><br>
        Once you have set up your Pera Algo Wallet account, click NEXT.
    </p>
    <div class="buttonContainer">
        <router-link to="/getting-started-step-2"><button class="backButton directionButton">BACK</button></router-link>
        <router-link to="/getting-started-step-4"><button class="directionButton">NEXT</button></router-link>
    </div>
</template>

<style lang="scss" scoped>
header {
    margin-top: 6%;
}

img {
    width: 200px;
    margin: 0;
}

button {
    margin-bottom: 3%;
    margin-top: 2%;
    min-width: 20vw;
}

.buttonContainer {
    display: flex;
    justify-content: space-between;
    margin: 3%;
}

@media (max-width: 800px) {
    button {
        min-width: 35vw;
    }
}
</style>

<script>
export default {
  mounted () {
    window.scrollTo(0, 0)
  }
}
</script>
