<template>
<div>
    <p class="darkBlueHeader spreadText">PRIVACY POLICY</p>
    <p>Welcome to Alchemon! Alchemon is owned and operated by Alchemon Inc. (Hereinafter referred to as “Alchemon”) Alchemon values your privacy and the protection of your personal data. This privacy policy describes what information we collect from you, how we collect it, how we use it, how we obtain your consent, how long we keep it in our databases and, if necessary, with whom we share it. By using the website and participating in the Alchemon game, you are accepting the practices described in this Privacy Policy. Your use of the platform and participation in the game is also subject to our <a href="https://alchemon.net/termsandconditions.html" target="_blank">Terms and Conditions</a>. This privacy policy may change from time to time. Your continued use of the website and the Alchemon game after we make changes to this Privacy Policy is deemed acceptance of those changes, so please check this policy periodically for updates. This Privacy Policy has been developed and is maintained in accordance with all applicable federal and international laws and regulations and, specifically, with the California Online Privacy Protection Act (CalOPPA - U.S. regulation) and the General Data Protection Regulation (GDPR - European regulation).</p>
    <p class="orangeHeader spreadText">1. GENERAL INFORMATION</p>
    <p>The personal data of the users that are collected and processed through: <a href="https://alchemon.net/" target="_blank">alchemon.net</a> will be under responsibility and in charge of: Alchemon Inc. (info at alchemon dot net).</p>
    <p class="orangeHeader spreadText">2. TYPES OF INFORMATION GATHERED</p>
    <p>The information we collect from our users helps us to effectively provide our platform and to personalize and continually improve the user experience on the platform. These are the types of information we collect:
    <ul>
        <li>Information You Give Us. You provide information when you upload, post, share, search, read, listen and view content within the platform, website and game, participate in the game and/or communicate with us through our contact information or through our communication channels such as Discord or Telegram. As a result of those actions, you may provide us with the following information: First and last name; Email address; User content; Any additional information relating to you that you provide to us directly through our platform or indirectly through our platform or online presence such as ‘cookies’. Alchemon will not collect any personally identifiable information about you, unless you provide it.</li>
        <li>Information Collected Automatically: By accessing, registering and using the platform and website you automatically provide us with the following information:</li>
        <ul>
            <li>The device and usage information you use to access the platform</li>
            <li>Your IP address</li>
            <li>Browser and device characteristics</li>
            <li>Operating system</li>
            <li>Referring URLs</li>
            <li>Your location</li>
            <li>Which parts of the website and platform you use most frequently</li>
        </ul>
    </ul>
    </p>
    <p>If you access the platform and website through a mobile phone, we will collect the following information:</p>
    <ul>
        <li>Mobile device ID</li>
        <li>Model and manufacturer</li>
        <li>Operating system </li>
        <li>Version information </li>
        <li>IP address</li>
    </ul>
    <p>We also may use these services:</p>
    <ul>
        <li>GOOGLE Analytics. We use Google Analytics provided by Google, Inc., USA (“Google”). These tool and technologies collect and analyze certain types of information, including IP addresses, device and software identifiers, referring and exit URLs, feature use metrics and statistics, media access control address (MAC Address), mobile unique device identifiers, and other similar information via the use of cookies. The information generated by Google Analytics (including your IP address) may be transmitted to and stored by Google on servers in the United States. We use the GOOGLE Analytics collection of data to enhance the platform and improve our service. Please consult Google's privacy policy here: <a href="https://policies.google.com/privacy" target="_blank">policies.google.com/privacy</a></li>
        <li>Social Media: On our platform you will find links and functions linked to different social networks, where you can share your information. The user will also be able to share information from their social networks through the platform or when logging in through their social network accounts. It is advisable to consult the privacy policy and data protection of each social media used on our platform.</li>
        <li>Telegram: <a href="https://telegram.org/privacy" target="_blank">telegram.org/privacy</a></li>
        <li>Discord: <a href="https://discord.com/privacy" target="_blank">discord.com/privacy</a></li>
        <li>Twitter: <a href="https://twitter.com/en/privacy" target="_blank">twitter.com/en/privacy</a></li>
    </ul>
    <p class="orangeHeader spreadText">3. HOW LONG WE KEEP YOUR DATA</p>
    <p>Personal data provided by users through the platform will be retained for the time necessary to provide the platform and the functionalities available in the game and the website. Alchemon may be allowed to retain personal data for a longer period whenever the user has given consent to such processing, as long as such consent is not withdrawn. Furthermore, Alchemon may be obliged to retain personal data for a longer period whenever required to do so for the performance of a legal obligation or upon order of an authority. Once the retention period expires, personal data shall be deleted. Therefore, the right to access, the right to erasure, the right to rectification and the right to data portability cannot be enforced after expiration of the retention period.</p>
    <p class="orangeHeader spreadText">4. HOW WE USE YOUR INFORMATION.</p>
    <p>In general, we use the information we collect primarily to provide, maintain, protect and improve our current platform and services. We use personal information collected through our site as described below and described elsewhere in this Policy to:</p>
    <ul>
        <li>Identify you as a user in our system.</li>
        <li>Provide functionalities within the website.</li>
        <li>Provide gaming functionalities such as trading or staking.</li>
        <li>Provide the raffles.</li>
        <li>Understand and improve your experience when participating in the game.</li>
        <li>Respond to your comments or questions through our support team.</li>
        <li>Send you related information, including confirmations, invoices, technical notices, updates, security alerts and support and administrative messages.</li>
        <li>Communicate with you about upcoming events, offers and news about content and services offered by Alchemon and our selected partners.</li>
        <li>Marketing purposes of Alchemon.</li>
        <li>Link or combine your information with other information we get from third parties to help understand your needs and provide you with better service.</li>
        <li>Protect, investigate and deter against fraudulent, unauthorized or illegal activity.</li>
    </ul>
    <p class="orangeHeader spreadText">5. HOW DO YOU GET MY CONSENT?</p>
    <p>By participating in the game, use the communication channels to communicate with us such as Discord and Telegram or our contact information, accepting the use of cookies by our website and providing personal information to us to communicate with you, you consent to our collection, storage and use of your information on the terms contained in this privacy policy.  You consent to the use of cookies on our platform when you give your acceptance through the pop-up window shown on the home page when you enter the platform. You may withdraw your consent by sending us your request via the contact information or the contact page.</p>
    <p class="orangeHeader spreadText">6. HOW WE SHARE INFORMATION</p>
    <p>The personal information of our users is an important and fundamental part of our business. Under no circumstances will we sell or share information with third parties that has not been previously authorized by the user or owner of the personal data. We share user information only and exclusively as described below:</p>
    <ul>
        <li>Third-Party Service Providers. We use the services of third parties to perform certain functions on the platform. For example, building and hosting the website, communicating with users (Discord, Telegram), analyzing data (Google Analytics), providing marketing services and providing search results. These third-party services and tools may have access to personal information needed to perform their functions, but may not use that information for other purposes. Information shared with these third-party services will be treated and stored in accordance with their respective privacy policies and our privacy policy.</li>
        <li>Business Transfers. In the event that Alchemon creates, merges with, or is acquired by another entity, your information will most likely be transferred. Alchemon will email you or place a prominent notice on our Platform before your information becomes subject to another privacy policy.</li>
        <li>Protection of Alchemon and others. We release personal information when we believe release is appropriate to comply with the law, enforce or apply our Terms and conditions and other agreements, or protect the rights, property, or safety of Alchemon, our users or others. This includes exchanging information with other companies and organizations for fraud protection and credit risk reduction.</li>
        <li>With Your Consent. Other than as set out above, you will receive notice when personally identifiable information about you might go to third parties, and you will have an opportunity to choose not to share the information.</li>
        <li>Anonymous Information. Alchemon uses the anonymous browsing information collected automatically by our servers primarily to help us administer and improve the Platform. We may also use aggregated anonymous information to provide information about the Platform to potential business partners and other unaffiliated entities. This information is not personally identifiable.</li>
        <li>Email Address. The email address that you supply to us for purposes of receiving our email communications will never be rented or sold to a third party.</li>
    </ul>
<p class="orangeHeader spreadText">7. PROTECTING YOUR INFORMATION</p>
    <p>Alchemon will make all reasonable efforts to protect the personal information of users it obtains, and the personal information will be protected by dedicated data security personnel. In order to prevent users' personal information from being illegally accessed, copied, modified, transmitted, lost, destroyed, processed or used in unexpected and unauthorized situations, Alchemon has and will continue to take the following measures to protect your personal information: 1) The user's personal information is encrypted and stored by adopting encryption technology, and is isolated by isolation technology. 2) When using personal information, such as personal information display and personal information association calculations, we will use a variety of data desensitization technologies including content replacement, encryption desensitization, etc. to enhance the security of personal information in use. 3) Establish a strict data use and access system, adopt strict data access authority control and multiple identity authentication technologies to protect personal information, and prevent data from being used in violation of regulations. Other security measures taken to protect personal information 1) Manage and regulate the storage and use of personal information by establishing a data classification and grading system, data security management specifications, and data security development specifications. 2) Data security personnel are responsible for security emergency response to promote and protect personal information security. 3. Notification of personal information security incidents 1) In the event of a security incident caused by personal information, Alchemon will report the first incident to the corresponding competent authority, and immediately carry out troubleshooting and emergency measures.</p>
<p class="orangeHeader spreadText">8. RIGHTS</p>
    <p>Users who provide information through our platform, as data subjects and data owners, have the right to access, rectify, download or delete their information, as well as to restrict and object to certain processing of their information. While some of these rights apply generally, others apply only in certain limited circumstances. We describe these rights below:</p>
        <ul>
            <li>Access and portability: to access and know what information is stored in our servers, you can send us your request through our contact information.</li>
            <li>Rectify, Restrict, Limit and Delete: You can also rectify, restrict, limit or delete much of your information.</li>
            <li>Right to be informed: Users of our platform will be informed, upon request, about what data we collect, how it is used, how long it is retained and whether it is shared with third parties.</li>
            <li>Object: When we process your information based on our legitimate interests as explained above, or in the public interest, you may object to this processing in certain circumstances. In such cases, we will stop processing your information unless we have compelling legitimate reasons to continue processing it or where it is necessary for legal reasons.</li>
            <li>Revoke consent: Where you have previously given your consent, such as to allow us to process and store your personal information, you have the right to revoke your consent to the processing and storage of your information at any time. For example, you may withdraw your consent by updating your settings. In certain cases, we may continue to process your information after you have withdrawn your consent if we have a legal basis for doing so or if your withdrawal of consent was limited to certain processing activities.</li>
            <li>Complaint: If you wish to file a complaint about our use of your information (and without prejudice to any other rights you may have), you have the right to do so with your local supervisory authority. Users can exercise all these rights by contacting us through the contact information or the contact page.</li>
            <li>Rights related to automated decision-making, including profiling: platform users may request that we provide a copy of the automated processing activities we conduct if they believe that data is being unlawfully processed.</li>
        </ul>
    <p>Users or owners of the personal information they provide through the platform and services may exercise these rights over their personal information at any time and without any limitation by sending us their request through our contact information.</p>
<p class="orangeHeader spreadText">9. CHILDREN’S ONLINE PRIVACY PROTECTION</p>
    <p>We comply with the requirements of the California Online Privacy Protection Act (CalOPPA – U.S regulation) and the GDPR (General Data Protection Regulation - European regulation) regarding the protection of the personal data of minors. We do not collect any information from anyone under the age of 13. Our platform and game is intended for people who are at least 13 years of age or older. If you become aware that a minor has provided us with personal information, please contact us. If we become aware that a minor under the age of 13 has provided us with personal information without proper authorization from his/her parents or legal guardians, we will take steps to delete that information, terminate that person's account, and restrict access to that person.</p>
<p class="orangeHeader spreadText">10. EDITING AND DELETING INFORMATION</p>
    <p>If you believe that any information we are holding on you is incorrect or incomplete, please write to or email us as soon as possible. We will promptly correct any information found to be incorrect. You can change, modify, rectify and delete your Information at any time, please contact us through the contact information. To opt-out of Alchemon email, follow the instructions included in the email. Your request should be processed within 48 hours.</p>
<p class="orangeHeader spreadText">11. THIRD PARTIES</p>
    <p>Except as otherwise expressly included in this Privacy Policy, this document addresses only the use and disclosure of information Alchemon collects from you. If you disclose your information to others, whether other users or suppliers on Alchemon, different rules may apply to their use or disclosure of the information you disclose to them. Alchemon does not control the privacy policies of third parties, and you are subject to the privacy policies of those third parties where applicable. Alchemon is not responsible for the privacy or security practices of other platforms on the Internet, even those linked to or from the Alchemon site. Alchemon encourages you to ask questions before you disclose your personal information to others.</p>
<p class="orangeHeader spreadText">12. CONTACT US </p>
<p>If you have questions or concerns about these Privacy Policy and the handling and security of your data, please contact us through our contact page or via the contact information below:
<br>info at alchemon dot com</p>
</div>
</template>

<style lang="scss" scoped>
ul {
    text-align: justify;
    margin: 0 5% 0 7%;
}
li {
    margin: 3% auto;
}
div {
    margin: 7% 0;
}
</style>

<script>
export default {
  mounted () {
    window.scrollTo(0, 0)
  }
}
</script>
